### ISSUE TITLE
* in logstash file input doesn't work (on Windows)

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex-attic/logsearch#100]
I'm struggling to get the [logstash file input to recognise wildcards for the `path` parameter](http://logstash.net/docs/1.1.13/inputs/file#setting_path).

Specifically, given the following set of log files:

```
C:\Users\David.Laing>dir \\pkh-ppe-web24\Logs\TradingApi.log*.log
 Volume in drive \\pkh-ppe-web24\Logs is Data
 Volume Serial Number is B01F-6AF1

 Directory of \\pkh-ppe-web24\Logs

26/07/2013  23:59         9,565,098 TradingApi.log20130726.log
27/07/2013  23:59        22,263,734 TradingApi.log20130727.log
28/07/2013  23:59        26,240,277 TradingApi.log20130728.log
29/07/2013  23:41        15,396,006 TradingApi.log20130729.log
30/07/2013  23:59         6,202,809 TradingApi.log20130730.log
31/07/2013  23:59         7,834,500 TradingApi.log20130731.log
01/08/2013  16:36         2,671,384 TradingApi.log20130801.log
               7 File(s)     90,173,808 bytes
               0 Dir(s)   5,455,089,664 bytes free
```

This works (ie, picks up new lines written to this file)

```
 file {
        type => "ci_log4net"
        path => "\\pkh-ppe-web24\Logs\TradingApi.log20130801.log"
        stat_interval => 1
        add_field => [ "service", "TradingApi" ]
        add_field => [ "@real_source_host", "pkh-ppe-web24" ]
        #debug => true
    }
```

This doesn't (ie, doesn't pick up new lines from any of the files)

```
    file {
        type => "ci_log4net"
        path => "\\pkh-ppe-web24\Logs\TradingApi.log*.log"
        stat_interval => 1
        add_field => [ "service", "TradingApi" ]
        add_field => [ "@real_source_host", "pkh-ppe-web24" ]
        #debug => true
    }
```

**Comment by Pragmateek** [comment]
Seems like this is an **escaping** issue => it should work too by escaping `"\"`: `\\\\pkh-ppe-web24\\Logs\\TradingApi.log2013080*.log`.
Though I prefer `"/"` too. :-)

**Comment by ghost** [comment]
logstash-input-file can't understood \\* on windows:
1.path => "F:\Elastic Stack\Apache Log Files\aa.log"
This works.

2.path => "F:/Elastic Stack/Apache Log Files/*.log"
This works.

3.path => "F:\Elastic Stack\Apache Log Files\\*.log"
This doesn't work!

Logstash got stuck at "Pipeline main started",without giving any error information!
It is a BUG! (How strange it is!)

(Note:It is not caused by "start_position","ignore_older" and the "sincedb".)
