### ISSUE TITLE
Fix elastichq "Unable to Connect to Server! Received Status Code: 0." startup message

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex-attic/logsearch#254]
When connecting to a cluster with the elastichq monitoring tool, eg via:

```
http://www.elastichq.org/app/?url=http://logsearch.cityindextest5.co.uk:80
```

you are greeted with a:

```
Error!
Unable to Connect to Server! Received Status Code: 0. A status code of 0, could mean the host is unreacheable or nothing is listening on the given port.
```

Following which the rest of the console loads and seems to work correctly.

At a guess, we're not proxying one of the ES monitoring urls correctly

**Comment by jerryhall** [comment]
Thanks gmcneel - worked like a charm.

**Comment by ulkas** [comment]
i can confirm @gmcneel solution works like charm. elasticsearch installed on separate ubuntu server machine, using the HQ from my localhost installation.
the config file is located in `/etc/elasticsearch/elasticsearch.yml` when installed from repository. restarting via `sudo service elasticsearch restart`

**Comment by rondoe** [comment]
thank you @gmcneel , perfect!

**Comment by rondoe** [comment]
according to http://stackoverflow.com/a/33723890 i also added `http.cors.allow-origin: "*"` to my `/etc/elasticsearch/elasticsearch.yml`. both hq and elasticsearch are running on same ubuntu machine.

**Comment by hectorqiuiscool** [comment]
Thinks very much!

I add these lines to `/etc/elasticsearch/elasticsearch.yml` and restart elasticsearch service, then it works for me.

```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

**Comment by federicodepro** [comment]
@gmcneel solution (http.cors.enabled: true) worked for me.

I´m running v1.7.x

**Comment by professordennis** [comment]
To monitore your instance Elasticsearch using ElasticHQ, follow these steps:
1 - Download the zip file Elasticsearch-HQ (from https://github.com/royrusso/elasticsearch-HQ, pressing the green button);
2 - Unzip it in your "/public_html/ElasticHQ" or "/var/www/ElasticHQ" folder, to access it locally.
3 - Access in your browser, pointing to "localhost/ElasticHQ" and put inside the top box, the right place where your Elasticsearch instance was installed. Ex. http://10.172.0.15:9200.
