### ISSUE TITLE
Saving Kibana Dashboard to Elastic Search fails with "405 PUT not allowed"

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex-attic/logsearch#33]
Attempting to save a Kibana Dashboard to Elastic Search fails with "405 PUT not allowed"

![screeny shot 27 jun 2013 23 34 51](https://f.cloud.github.com/assets/227505/719193/f3252e6c-df79-11e2-8769-acb4c2be7358.png)

![screeny shot 27 jun 2013 23 35 08](https://f.cloud.github.com/assets/227505/719191/f1c6ae56-df79-11e2-9de3-c768993001f7.png)

**Comment by pratik705** [comment]
What is the fix for apache ? I am hitting exact issue.
