### ISSUE TITLE
Assess/Retire project

### ISSUE THREAD

**Issue by sopel** [cityindex-attic/logsearch#371]
This project seems to have reached its end of life and is due for retirement to the [CityIndex Attic](https://github.com/orgs/cityindex-attic) accordingly - the goal of this issue is to allow final stakeholder discussion/confirmation and identify resulting activities, if any.

**Comment by sopel** [comment]
This project is superseded by various projects under the top level GitHub organization [logsearch](https://github.com/logsearch), see also  [Logsearch](http://www.logsearch.io/).
* (/) All stakeholders have agreed to retire [cityindex/logsearch](https://github.com/cityindex/logsearch) to [cityindex-attic/logsearch](https://github.com/cityindex-attic/logsearch) accordingly.

**Comment by mrdavidlaing** [comment]
Godspeed cityindex/logsearch.  You got us going in the right direction, until we were seduced by the whiles of BOSH...

**Comment by sopel** [comment]
:information_source: I'll disable the Flowdock notifications early in order to not flood the flow with the upcoming 64 issue closings.

**Comment by dpb587** [comment]
Good idea; and I've unwatched the repo now.
