### ISSUE TITLE
Fix Vagrant provisioning not working on Windows hosts

### ISSUE THREAD

**Issue by sopel** [cityindex-attic/logsearch#7]
There seem to be an issue with the provisioning when running `vagrant up` (or `vagrant provision`) on a Windows host (Windows 7, 64-bit, VirtualBox 4.2.12, Vagrant 1.2.2):

```
[default] Running provisioner: shell...
[default] Running: vagrant-shell20130604-8728-1gcywnb
stdin: is not a tty
ln:
failed to create symbolic link `/home/vagrant/current/app'
: Protocol error
: Protocol error

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell
```

This obviously doesn't yield a properly configured instance, running the provisioning script manually after the fact doesn't work either due to the same error.

**Comment by geekdenz** [comment]
I have the same issue on Ubuntu 15.04 with VirtualBox 5.0.4.

Any work arounds?

I've found that creating the symlinks on the host OS works, but we use Puppet to provision the VM and they symlinks should also be in production which should also be in the Puppet scripts. So, this is still an issue.
